// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteNewPassword(arg1) {
  return window['go']['cognito']['CognitoAuth']['CompleteNewPassword'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['cognito']['CognitoAuth']['SignIn'](arg1, arg2);
}
